//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPU
    {
        public int id { get; set; }
        public string socket { get; set; }
        public string name { get; set; }
        public Nullable<int> cores { get; set; }
        public Nullable<int> threads { get; set; }
        public Nullable<double> frequency { get; set; }
        public Nullable<int> price { get; set; }
    }
}
