//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demand
    {
        public int id { get; set; }
        public string cpu { get; set; }
        public string motherboard { get; set; }
        public string ram { get; set; }
        public string graphiccard { get; set; }
        public string stockage { get; set; }
        public string powerSupplay { get; set; }
        public string cooling { get; set; }
        public string case1 { get; set; }
        public Nullable<decimal> price { get; set; }
    }
}
