//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PCEntities : DbContext
    {
        public PCEntities()
            : base("name=PCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<case1> case1 { get; set; }
        public virtual DbSet<cooling> coolings { get; set; }
        public virtual DbSet<CPU> CPUs { get; set; }
        public virtual DbSet<Demand> Demands { get; set; }
        public virtual DbSet<graphicCard> graphicCards { get; set; }
        public virtual DbSet<motherboard> motherboards { get; set; }
        public virtual DbSet<powerSupply> powerSupplies { get; set; }
        public virtual DbSet<RAM> RAMs { get; set; }
        public virtual DbSet<stockage> stockages { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
